version: "3"
services:
  web:
    build: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    ports:
      - "8090:8090"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
        - 27017
